name: espanso-translate
parent: default

global_vars:
  # Your open-ai key
  - name: "OPENAI_KEY"
    type: "echo"
    params:
      echo: ""
  - name: "AI_MODEL"
    type: "echo"
    params:
      echo: "gpt-3.5-turbo"
  # Translate to what?
  - name: "DEST_LANG"
    type: "echo"
    params:
      echo: "Japanese"
  # Please don't change this
  - name: "SCRIPT_PATH"
    type: "echo"
    params:
      echo: '"$CONFIG/match/packages/espanso-translate/scripts/trans.py"'
  # Custom Python path for venv user
  - name: "PYTHON"
    type: "echo"
    params:
      echo: "/usr/bin/python"
  # Shell command proxy, e.g. http_proxy=http://127.0.0.1:7223
  - name: "PROXY"
    type: "echo"
    params:
      echo: ""

    replace: "{{output}}"
    vars:
      - name: openai_key
        type: echo
        params:
          echo: "{{OPENAI_KEY}}"
      - name: output
        type: shell
        params:
          cmd: '{{PROXY}} {{PYTHON}} {{SCRIPT_PATH}} "{{DEST_LANG}}" "{{p}}"'
